# Generated by Django 4.2 on 2023-07-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0002_rename_ftype_subproduct_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('video blogs', 'Video Blogs'), ('home', 'Home')], max_length=50)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('keywords', models.TextField()),
                ('backlinks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubproductSeoContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_desc', models.TextField()),
                ('keywords', models.TextField()),
                ('external_links', models.TextField()),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproduct_external_links', to='appagri.subproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog_meta',
        ),
        migrations.DeleteModel(
            name='Blogs_key',
        ),
        migrations.DeleteModel(
            name='Contact_key',
        ),
        migrations.DeleteModel(
            name='Contact_meta',
        ),
        migrations.DeleteModel(
            name='Home_key',
        ),
        migrations.DeleteModel(
            name='Home_meta',
        ),
        migrations.DeleteModel(
            name='Home_Page_Links',
        ),
        migrations.DeleteModel(
            name='Product_Page_Links',
        ),
        migrations.DeleteModel(
            name='Videos_key',
        ),
        migrations.DeleteModel(
            name='Videos_meta',
        ),
    ]
