# Generated by Django 4.2 on 2023-07-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0003_seocontents_subproductseocontents_delete_blog_meta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubproductSeoContents',
        ),
    ]
