# Generated by Django 4.2 on 2023-08-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0004_delete_subproductseocontents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10, null=True, unique=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('comments', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('type_of_image', models.CharField(choices=[('awards', 'Awards'), ('media coverages', 'Media Coverages'), ('approvals and licenses', 'Approvals and Licenses')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoPageExtLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('video blogs', 'Video Blogs')], max_length=50)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('keywords', models.TextField()),
                ('backlinks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subproduct_External_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_desc', models.TextField()),
                ('keywords', models.TextField()),
                ('external_links', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='product_external_links',
            name='product',
        ),
        migrations.DeleteModel(
            name='SeoContents',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.RenameField(
            model_name='subproduct',
            old_name='discount',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='subproduct',
            old_name='price',
            new_name='sales_price',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='hedding',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='avilability',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='product_type',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_heading',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogs',
            name='embed_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='video_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='video_heading',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='backlinks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Product_External_links',
        ),
        migrations.AddField(
            model_name='subproduct_external_links',
            name='subproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproduct_external_links', to='appagri.subproduct'),
        ),
        migrations.AddField(
            model_name='comments',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appagri.blogs'),
        ),
    ]
