# Generated by Django 4.2 on 2023-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0005_comments_contacts_credentials_seopageextlinks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compare_key',
        ),
        migrations.DeleteModel(
            name='Compare_meta',
        ),
        migrations.DeleteModel(
            name='Homeimg',
        ),
        migrations.DeleteModel(
            name='Homeproblem',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Product_Gallery',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order_no']},
        ),
        migrations.AddField(
            model_name='product',
            name='order_no',
            field=models.IntegerField(null=True),
        ),
    ]
