# Generated by Django 4.2 on 2023-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0006_delete_compare_key_delete_compare_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
