# Generated by Django 4.2 on 2023-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0008_alter_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home_information',
            name='imageone',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home_information',
            name='imagethree',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home_information',
            name='imagetwo',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Highlight_image1',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Highlight_image2',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Highlight_image3',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='spimage',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
    ]
