# Generated by Django 4.2 on 2024-01-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0011_product_slug_subproduct_order_no_subproduct_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopageextlinks',
            name='backlinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seopageextlinks',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seopageextlinks',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seopageextlinks',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
