# Generated by Django 4.2 on 2024-01-16 10:14

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0014_review_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=1000, null=True)),
                ('text2', models.CharField(blank=True, max_length=1000, null=True)),
                ('text3', models.CharField(blank=True, max_length=1000, null=True)),
                ('text4', models.CharField(blank=True, max_length=1000, null=True)),
                ('text5', models.CharField(blank=True, max_length=1000, null=True)),
                ('text6', models.CharField(blank=True, max_length=1000, null=True)),
                ('text7', models.CharField(blank=True, max_length=1000, null=True)),
                ('text8', models.CharField(blank=True, max_length=1000, null=True)),
                ('text9', models.CharField(blank=True, max_length=1000, null=True)),
                ('text10', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='seopageextlinks',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('video blogs', 'Video Blogs'), ('kcenter', 'K Center')], max_length=50),
        ),
        migrations.CreateModel(
            name='KitComponentSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_component', models.CharField(max_length=500)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('customer_name', models.CharField(max_length=500, null=True)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('total_amount', models.CharField(blank=True, default='0.00', max_length=10, null=True)),
                ('discount_price', models.CharField(blank=True, default='0.00', max_length=10, null=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=500)),
                ('component_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('component_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.subproduct')),
            ],
        ),
    ]
