# Generated by Django 4.2 on 2024-01-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0016_alter_product_highlight_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='rateing',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='spinfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
