# Generated by Django 4.2 on 2024-02-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0017_alter_subproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt',
            field=models.CharField(default='', max_length=500),
        ),
    ]
