# Generated by Django 4.2 on 2024-02-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0018_banner_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '3. Upload Banner Images', 'verbose_name_plural': '3. Upload Banner Images'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': '9. Enter Blogs', 'verbose_name_plural': '9. Enter Blogs'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': '7. Upload Collaboration Images', 'verbose_name_plural': '7. Upload Collaboration Images'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '1. Get Blogs Comments', 'verbose_name_plural': '1. Get Blogs Comments'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': '2. Get User Messages', 'verbose_name_plural': '2. Get User Messages'},
        ),
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': '8. Upload Credential Images', 'verbose_name_plural': '8. Upload Credential Images'},
        ),
        migrations.AlterModelOptions(
            name='highlights',
            options={'verbose_name': '4. Upload Website Highlights', 'verbose_name_plural': '4. Upload Website Highlights'},
        ),
        migrations.AlterModelOptions(
            name='home_information',
            options={'verbose_name': '5. Upload Website Info & Images', 'verbose_name_plural': '5. Upload Website Info & Images'},
        ),
        migrations.AlterModelOptions(
            name='kcenter',
            options={'verbose_name': '10. Enter K Center Data', 'verbose_name_plural': '10. Enter K Center Data'},
        ),
        migrations.AlterModelOptions(
            name='kitcomponent',
            options={'verbose_name': "4. Enter Kit's Product details", 'verbose_name_plural': "4. Enter Kit's Product details"},
        ),
        migrations.AlterModelOptions(
            name='kitcomponentselected',
            options={'verbose_name': '5. User Selected Kit Products', 'verbose_name_plural': '5. User Selected Kit Products'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': '2. Upload Website Logo Image', 'verbose_name_plural': '2. Upload Website Logo Image'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order_no'], 'verbose_name': '1. Enter Product Categories', 'verbose_name_plural': '1. Enter Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '6. Get Product Reviews', 'verbose_name_plural': '6. Get Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='seopageextlinks',
            options={'verbose_name': '1. Enter SEO Contents', 'verbose_name_plural': '1. Enter SEO Contents'},
        ),
        migrations.AlterModelOptions(
            name='subproduct',
            options={'verbose_name': '2. Enter Products', 'verbose_name_plural': '2. Enter Products'},
        ),
        migrations.AlterModelOptions(
            name='subproduct_external_links',
            options={'verbose_name': '3. Enter Product SEO Contents', 'verbose_name_plural': '3. Enter Product SEO Contents'},
        ),
        migrations.AlterModelOptions(
            name='webinfo',
            options={'verbose_name': '6. Enter Our Brand Details', 'verbose_name_plural': '6. Enter Our Brand Details'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='credentials',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='home_information',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kcenter',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='logo',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='brands',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
