# Generated by Django 4.2 on 2024-02-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0020_alter_banner_options_alter_blogs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'c. Upload Banner Images', 'verbose_name_plural': 'c. Upload Banner Images'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'i. Enter Blogs', 'verbose_name_plural': 'i. Enter Blogs'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'g. Upload Collaboration Images', 'verbose_name_plural': 'g. Upload Collaboration Images'},
        ),
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'h. Upload Credential Images', 'verbose_name_plural': 'h. Upload Credential Images'},
        ),
        migrations.AlterModelOptions(
            name='highlights',
            options={'verbose_name': 'd. Upload Website Highlights', 'verbose_name_plural': 'd. Upload Website Highlights'},
        ),
        migrations.AlterModelOptions(
            name='home_information',
            options={'verbose_name': 'e. Upload Website Info & Images', 'verbose_name_plural': 'e. Upload Website Info & Images'},
        ),
        migrations.AlterModelOptions(
            name='kcenter',
            options={'verbose_name': 'j. Enter K Center Data', 'verbose_name_plural': 'j. Enter K Center Data'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'b. Upload Website Logo Image', 'verbose_name_plural': 'b. Upload Website Logo Image'},
        ),
        migrations.AlterModelOptions(
            name='seopageextlinks',
            options={'verbose_name': 'a. Enter SEO Contents', 'verbose_name_plural': 'a. Enter SEO Contents'},
        ),
        migrations.AlterModelOptions(
            name='webinfo',
            options={'verbose_name': 'f. Enter Our Brand Details', 'verbose_name_plural': 'f. Enter Our Brand Details'},
        ),
    ]
