# Generated by Django 4.2 on 2024-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0022_alter_comments_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlights',
            options={'verbose_name': 'd. Upload Cross Promotion Content', 'verbose_name_plural': 'd.  Upload Cross Promotion Content'},
        ),
        migrations.RemoveField(
            model_name='highlights',
            name='text',
        ),
        migrations.AddField(
            model_name='highlights',
            name='alt',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='highlights',
            name='text1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
