# Generated by Django 4.2 on 2024-04-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0024_alter_product_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Terrace Gardening', 'Terrace Gardening'), ('Irrigation Solutions', 'Irrigation Solutions')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
