# Generated by Django 4.2 on 2024-04-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0025_product_category_alter_product_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
