# Generated by Django 4.2 on 2024-04-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0026_banner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitcomponentselected',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='kitcomponentselected',
            name='customer_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='kitcomponentselected',
            name='discount_price',
            field=models.CharField(default='0.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='kitcomponentselected',
            name='email_id',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='kitcomponentselected',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='kitcomponentselected',
            name='quantity',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='kitcomponentselected',
            name='total_amount',
            field=models.CharField(default='0.00', max_length=10),
        ),
    ]
