# Generated by Django 4.2 on 2024-04-19 11:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0027_alter_kitcomponentselected_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='r_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='review_token',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='whatsapp_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.review')),
            ],
            options={
                'verbose_name': 's. Get Product Reviews',
                'verbose_name_plural': 's. Get Product Reviews',
            },
        ),
    ]
