# Generated by Django 4.2 on 2024-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0029_atscontactinfo_atsinfo_atsintro_atsseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip_address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
