# Generated by Django 4.2 on 2024-05-15 09:44

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0031_review_date_review_is_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_title', models.CharField(max_length=500)),
                ('ppt', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'z6. Enter ATM Roadmap Details',
                'verbose_name_plural': 'z6. Enter ATM Roadmap Details',
            },
        ),
        migrations.RemoveField(
            model_name='atscontactproductinfo',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='atsseller',
            name='seller_product_images',
        ),
        migrations.AddField(
            model_name='atscontactinfo',
            name='contact_company_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='atscontactinfo',
            name='contact_company_logo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ATSSellerProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_product_images', cloudinary.models.CloudinaryField(max_length=255)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.atsseller')),
            ],
        ),
        migrations.CreateModel(
            name='ATSContactProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', cloudinary.models.CloudinaryField(default='', max_length=255)),
                ('seller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appagri.atscontactinfo')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.atscontactproductinfo')),
            ],
            options={
                'verbose_name': 'z5. Enter ATM Supplier Product Images',
                'verbose_name_plural': 'z5. Enter ATM Supplier Product Images',
            },
        ),
    ]
