# Generated by Django 4.2 on 2024-05-24 08:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0032_atsroadmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exclusive_highlight_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='exclusive_img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='exclusive_img_alt',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
