# Generated by Django 4.2 on 2024-05-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0033_product_exclusive_highlight_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
