# Generated by Django 4.2 on 2024-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0034_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsinfo',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
