# Generated by Django 4.2 on 2024-06-01 11:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0035_atsinfo_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_img', cloudinary.models.CloudinaryField(max_length=255)),
                ('featured_alt', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'z6. Upload Featured Listing Images',
                'verbose_name_plural': 'z6. Upload Featured Listing Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='background_gif',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='exclusive_highlight_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='exclusive_img_alt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
