# Generated by Django 4.2 on 2024-06-08 05:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0036_featuredlisting_product_background_gif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exclusive_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
    ]
