# Generated by Django 4.2 on 2024-06-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0037_alter_product_exclusive_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
