# Generated by Django 4.2 on 2024-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0038_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='subject',
        ),
        migrations.AddField(
            model_name='contacts',
            name='place',
            field=models.CharField(default='', max_length=255),
        ),
    ]
