# Generated by Django 4.2 on 2024-06-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0039_remove_contacts_subject_contacts_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
