# Generated by Django 4.2 on 2024-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0040_alter_contacts_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webinfo',
        ),
        migrations.AlterModelOptions(
            name='atscontactinfo',
            options={'verbose_name': 'Enter ATM Supplier Info', 'verbose_name_plural': 'Enter ATM Supplier Info'},
        ),
        migrations.AlterModelOptions(
            name='atscontactproductimages',
            options={'verbose_name': 'Enter ATM Supplier Product Images', 'verbose_name_plural': 'Enter ATM Supplier Product Images'},
        ),
        migrations.AlterModelOptions(
            name='atscontactproductinfo',
            options={'verbose_name': 'Enter ATM Supplier Product Info', 'verbose_name_plural': 'Enter ATM Supplier Product Info'},
        ),
        migrations.AlterModelOptions(
            name='atsinfo',
            options={'verbose_name': 'Global Agritech & ATM: Enter Category Info', 'verbose_name_plural': 'Global Agritech & ATM: Enter Category Info'},
        ),
        migrations.AlterModelOptions(
            name='atsintro',
            options={'verbose_name': 'Enter ATM Introduction', 'verbose_name_plural': 'Enter ATM Introduction'},
        ),
        migrations.AlterModelOptions(
            name='atsroadmap',
            options={'verbose_name': 'ATM: Enter Roadmap Details', 'verbose_name_plural': 'ATM: Enter Roadmap Details'},
        ),
        migrations.AlterModelOptions(
            name='atsseller',
            options={'verbose_name': 'Get ATM Seller Enquiry & Feedback', 'verbose_name_plural': 'Get ATM Seller Enquiry & Feedback'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Upload Banner Images', 'verbose_name_plural': 'Upload Banner Images'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Post Blogs', 'verbose_name_plural': 'Post Blogs'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Home & About Us: Upload Collaboration Images', 'verbose_name_plural': 'Home & About Us: Upload Collaboration Images'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Get Comments for Blogs', 'verbose_name_plural': 'Get Comments for Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Get User Messages', 'verbose_name_plural': 'Get User Messages'},
        ),
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'Upload Credential Images', 'verbose_name_plural': 'Upload Credential Images'},
        ),
        migrations.AlterModelOptions(
            name='featuredlisting',
            options={'verbose_name': 'Upload Featured Listing Images', 'verbose_name_plural': 'Upload Featured Listing Images'},
        ),
        migrations.AlterModelOptions(
            name='highlights',
            options={'verbose_name': 'Enter Cross Promotion Content', 'verbose_name_plural': 'Enter Cross Promotion Content'},
        ),
        migrations.AlterModelOptions(
            name='home_information',
            options={'verbose_name': 'Enter Website Introduction', 'verbose_name_plural': 'Enter Website Introduction'},
        ),
        migrations.AlterModelOptions(
            name='kcenter',
            options={'verbose_name': 'Enter KCenter Details', 'verbose_name_plural': 'Enter KCenter Details'},
        ),
        migrations.AlterModelOptions(
            name='kitcomponent',
            options={'verbose_name': 'Enter Flexi Kits Product details', 'verbose_name_plural': 'Enter Flexi Kits Product details'},
        ),
        migrations.AlterModelOptions(
            name='kitcomponentselected',
            options={'verbose_name': 'Get User Selected Kit Products', 'verbose_name_plural': 'Get User Selected Kit Products'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Upload Website Logo', 'verbose_name_plural': 'Upload Website Logo'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order_no'], 'verbose_name': 'Enter Product Categories Data', 'verbose_name_plural': 'Enter Product Categories Data'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': "Get User's Product Reviews", 'verbose_name_plural': "Get User's Product Reviews"},
        ),
        migrations.AlterModelOptions(
            name='reviewresponse',
            options={'verbose_name': "Admin Response to User's Reviews", 'verbose_name_plural': "Admin Response to User's Reviews"},
        ),
        migrations.AlterModelOptions(
            name='seopageextlinks',
            options={'verbose_name': 'Enter SEO Content Page Wise', 'verbose_name_plural': 'Enter SEO Content Page Wise'},
        ),
        migrations.AlterModelOptions(
            name='subproduct',
            options={'verbose_name': 'Enter Products Data', 'verbose_name_plural': 'Enter Products Data'},
        ),
        migrations.AlterModelOptions(
            name='subproduct_external_links',
            options={'verbose_name': 'Enter Products SEO Contents', 'verbose_name_plural': 'Enter Products SEO Contents'},
        ),
        migrations.AddField(
            model_name='home_information',
            name='Kannada_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='seopageextlinks',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('video blogs', 'Video Blogs'), ('agritech mart', 'Agritech Mart'), ('kcenter', 'K Center')], max_length=50),
        ),
    ]
