# Generated by Django 4.2 on 2024-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0043_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
