# Generated by Django 4.2 on 2024-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0044_alter_contactnumber_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnumber',
            name='is_seen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_seen',
            field=models.BooleanField(null=True),
        ),
    ]
