# Generated by Django 4.2 on 2024-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0045_contactnumber_is_seen_contacts_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnumber',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
