# Generated by Django 4.2 on 2024-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0046_contactnumber_city_contactnumber_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnumber',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='region',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='stateDistrict',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
