# Generated by Django 4.2 on 2024-09-11 09:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0047_contactnumber_district_contactnumber_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=1000, null=True)),
                ('text2', models.CharField(blank=True, max_length=1000, null=True)),
                ('text3', models.CharField(blank=True, max_length=1000, null=True)),
                ('text4', models.CharField(blank=True, max_length=1000, null=True)),
                ('text5', models.CharField(blank=True, max_length=1000, null=True)),
                ('text6', models.CharField(blank=True, max_length=1000, null=True)),
                ('text7', models.CharField(blank=True, max_length=1000, null=True)),
                ('text8', models.CharField(blank=True, max_length=1000, null=True)),
                ('text9', models.CharField(blank=True, max_length=1000, null=True)),
                ('text10', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Enter K Center Data',
                'verbose_name_plural': 'Enter K Center Data',
            },
        ),
        migrations.RemoveField(
            model_name='kcentertopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kcentertopic',
            name='ktopictext',
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kcentertopic',
            name='text8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='kcentercategories',
        ),
    ]
