# Generated by Django 4.2 on 2024-09-24 10:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0048_kcenter_remove_kcentertopic_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='Highlight_image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='Highlight_image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='Highlight_image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='background_gif',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='exclusive_highlight_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='exclusive_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='exclusive_img_alt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='pinfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='sub_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='text1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='text3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
