# Generated by Django 4.2 on 2024-09-25 11:43

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0049_subproduct_highlight_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Terrace Gardening', 'Terrace Gardening')], max_length=200, null=True)),
                ('name', models.CharField(max_length=255)),
                ('order_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enter_Main_category',
                'verbose_name_plural': 'Enter_Main_category',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('order_no', models.IntegerField(blank=True, null=True)),
                ('spimage', models.ImageField(null=True, upload_to='')),
                ('alt', models.CharField(blank=True, default='', max_length=500)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spinfo', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rateing', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('Key_1', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_1', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_2', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_2', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_3', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_3', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_4', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_4', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_5', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_5', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_6', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_6', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_7', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_7', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_8', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_8', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_9', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_9', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_10', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_10', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_11', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_11', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_12', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_12', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_13', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_13', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_14', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_14', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_15', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_15', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Enter_Product data',
                'verbose_name_plural': 'Enter_Product data',
            },
        ),
        migrations.CreateModel(
            name='Subproduct_External_links1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_desc', models.TextField()),
                ('keywords', models.TextField()),
                ('external_links', models.TextField()),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproduct_external_links', to='appagri.product1')),
            ],
            options={
                'verbose_name': 'Enter Products SEO Contents---1',
                'verbose_name_plural': 'Enter Products SEO Contents---1',
            },
        ),
        migrations.CreateModel(
            name='sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order_no', models.IntegerField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('backlinks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('alt', models.CharField(blank=True, default='', max_length=500)),
                ('pinfo', models.TextField(blank=True, null=True)),
                ('Highlight_image1', models.ImageField(null=True, upload_to='')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('Highlight_image2', models.ImageField(null=True, upload_to='')),
                ('text2', models.CharField(blank=True, max_length=255, null=True)),
                ('Highlight_image3', models.ImageField(null=True, upload_to='')),
                ('text3', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('background_gif', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('exclusive_img', models.ImageField(null=True, upload_to='')),
                ('exclusive_img_alt', models.CharField(blank=True, max_length=500, null=True)),
                ('exclusive_highlight_text', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.main_category')),
            ],
            options={
                'verbose_name': 'Enter_Sub_category',
                'verbose_name_plural': 'Enter_Sub_category',
                'ordering': ['order_no'],
            },
        ),
        migrations.AddField(
            model_name='product1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.sub_cat'),
        ),
        migrations.CreateModel(
            name='KitComponentSelected1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_component', models.CharField(max_length=500)),
                ('quantity', models.CharField(default='', max_length=255)),
                ('customer_name', models.CharField(default='', max_length=500)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('email_id', models.EmailField(default='', max_length=254)),
                ('address', models.TextField(default='')),
                ('total_amount', models.CharField(default='0.00', max_length=10)),
                ('discount_price', models.CharField(default='0.00', max_length=10)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.product1')),
            ],
            options={
                'verbose_name': 'Get User Selected Kit Products---1',
                'verbose_name_plural': 'Get User Selected Kit Products---1',
            },
        ),
        migrations.CreateModel(
            name='KitComponent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=500)),
                ('component_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('component_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.product1')),
            ],
            options={
                'verbose_name': 'Enter Flexi Kits Product details---1',
                'verbose_name_plural': 'Enter Flexi Kits Product details---1',
            },
        ),
    ]
