# Generated by Django 4.2 on 2024-09-25 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0050_main_category_product1_subproduct_external_links1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitcomponent1',
            name='component_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product1',
            name='spimage',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sub_cat',
            name='Highlight_image1',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sub_cat',
            name='Highlight_image2',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sub_cat',
            name='Highlight_image3',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sub_cat',
            name='exclusive_img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sub_cat',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
    ]
