# Generated by Django 5.1.5 on 2025-02-01 05:25

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0052_kcentercategories_newone_sess_delete_kcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcomponent1',
            name='subproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appagri.subproduct'),
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=500)),
                ('component_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('component_sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component_quantity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.subproduct')),
            ],
            options={
                'verbose_name': 'Flexi Kit Component',
                'verbose_name_plural': 'Flexi Kit Components',
            },
        ),
        migrations.CreateModel(
            name='KitComponentSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_name', models.CharField(default='', max_length=500)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('email_id', models.EmailField(default='', max_length=254)),
                ('address', models.TextField(default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.subproduct')),
                ('selected_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.kitcomponent')),
            ],
            options={
                'verbose_name': 'User Selected Kit Products',
                'verbose_name_plural': 'User Selected Kit Products',
            },
        ),
        migrations.CreateModel(
            name='Subproduct_External_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_desc', models.TextField()),
                ('keywords', models.TextField()),
                ('external_links', models.TextField()),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproduct_external_links', to='appagri.subproduct')),
            ],
            options={
                'verbose_name': 'Enter Products SEO Contents',
                'verbose_name_plural': 'Enter Products SEO Contents',
            },
        ),
    ]
