# Generated by Django 5.1.5 on 2025-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0053_kitcomponent1_subproduct_kitcomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pinfo',
            field=models.TextField(null=True),
        ),
    ]
