# Generated by Django 5.1.5 on 2025-02-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0054_alter_product_pinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
