# Generated by Django 5.1.5 on 2025-02-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0055_alter_subproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pinfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
